### ISSUE TITLE
Starter TODO list

### ISSUE THREAD

**Issue by paulstroot** [ocupop/wordpress_starter#1]
### Wordpress Starter Wish List

**For Docker Setup**
- [ ] WP-CLI	
- [ ] PhpMyAdmin
- [ ] MySql Database, with initial import from .sql file
- [ ] Access to edit root level files. I.e. .htaccess, wp-admin, etc.
- [ ] Wordpress core install, without storing WP files in repository
- [ ] Install all recommended plug-ins, without storing code in starter repository (install using WP-CLI)
- [ ] Default starter theme installed and activated
- [ ] One example custom plug-in
- [ ] Local SSL and ngix might be nice, but not required

**Other**
- [ ] Tailwind
- [ ] Compiled JS
- [ ] Possibly an example theme.json file
- [ ] Documentation on how to make the starter theme a FSE block theme
- [ ] Accessible dropdown navigation
- [ ] Perhaps a mega-menu?
- [ ] Simple javascript components such as dropdown, accordion, expander
- [ ] Carousel
